# Generated by Django 3.2.6 on 2021-09-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsiteCrudEventos', '0002_publico_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='id_estabelecimento',
            field=models.IntegerField(null=True),
        ),
    ]
