# Generated by Django 3.2.4 on 2021-08-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('tipo', models.CharField(max_length=100, verbose_name='tipo')),
                ('rua', models.CharField(max_length=100, verbose_name='rua')),
                ('cep', models.CharField(max_length=100, verbose_name='cep')),
                ('cidade', models.CharField(max_length=100, verbose_name='cidade')),
            ],
        ),
    ]
