# Generated by Django 3.2.4 on 2021-08-11 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0004_estabelecimentos_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtdPessoas', models.IntegerField(verbose_name='qtdPessoas')),
                ('horaInicial', models.DateField(verbose_name='horaInicial')),
                ('horaFinal', models.DateField(verbose_name='horaFinal')),
                ('id_estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appsite.estabelecimentos')),
            ],
        ),
        migrations.CreateModel(
            name='PublicoGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('telefone', models.CharField(max_length=50, verbose_name='telefone')),
                ('cidade', models.CharField(max_length=100, verbose_name='cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Publico_Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appsite.eventos')),
                ('id_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appsite.publicogeral')),
            ],
        ),
    ]
