# Generated by Django 3.2.4 on 2021-08-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0005_eventos_publico_eventos_publicogeral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='horaFinal',
            field=models.DateTimeField(verbose_name='horaFinal'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='horaInicial',
            field=models.DateTimeField(verbose_name='horaInicial'),
        ),
    ]
