# Generated by Django 3.2.4 on 2021-08-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0006_auto_20210811_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicogeral',
            name='email',
            field=models.CharField(max_length=100, null=True, verbose_name='email'),
        ),
    ]
