# Generated by Django 3.2.4 on 2021-08-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0008_eventos_dataevento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='horaFinal',
            field=models.CharField(max_length=100, verbose_name='horaFinal'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='horaInicial',
            field=models.CharField(max_length=100, verbose_name='horaInicial'),
        ),
    ]
