# Generated by Django 3.2.4 on 2021-08-16 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0009_auto_20210816_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='local',
            field=models.CharField(max_length=100, null=True, verbose_name='local'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='id_estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appsite.publicogeral'),
        ),
    ]
