# Generated by Django 3.1.7 on 2021-08-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0010_auto_20210816_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimentos',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publico_eventos',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publicogeral',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
