# Generated by Django 3.2.4 on 2021-08-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0011_auto_20210818_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gatilhos_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_column', models.CharField(max_length=100, verbose_name='changed_column')),
                ('data_changed', models.DateTimeField(verbose_name='data_changed')),
                ('old_value', models.CharField(max_length=100, verbose_name='old_value')),
                ('new_value', models.CharField(max_length=100, verbose_name='new_value')),
                ('operation', models.CharField(max_length=100, verbose_name='operation')),
            ],
        ),
        migrations.AlterField(
            model_name='estabelecimentos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publico_eventos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publicogeral',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
