# Generated by Django 3.2.4 on 2021-08-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0012_auto_20210820_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimentos',
            name='tipoUsuario',
            field=models.CharField(max_length=100, null=True, verbose_name='tipoUsuario'),
        ),
    ]
