# Generated by Django 3.2.4 on 2021-08-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0013_estabelecimentos_tipousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimentos',
            name='senha',
            field=models.CharField(max_length=100, null=True, verbose_name='senha'),
        ),
    ]
