# Generated by Django 3.2.4 on 2021-08-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0016_alter_eventos_id_estabelecimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimentos',
            name='senha',
        ),
        migrations.AlterField(
            model_name='estabelecimentos',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='publicogeral',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='email'),
        ),
    ]
