# Generated by Django 3.2.4 on 2021-08-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0019_auto_20210823_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='descricao',
            field=models.CharField(max_length=100, null=True, verbose_name='descricao'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='titulo',
            field=models.CharField(max_length=100, null=True, verbose_name='titulo'),
        ),
    ]
