# Generated by Django 3.2.4 on 2021-08-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0020_auto_20210823_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='imagem',
            new_name='foto',
        ),
    ]
