# Generated by Django 3.2.4 on 2021-08-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0022_auto_20210823_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimentos',
            name='foto',
            field=models.FileField(null=True, upload_to='imgUser/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='publicogeral',
            name='foto',
            field=models.FileField(null=True, upload_to='imgUser/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='estabelecimentos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gatilhos_users',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publico_eventos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publicogeral',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
