# Generated by Django 3.2.4 on 2021-08-29 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0023_auto_20210826_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimentos',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='estabelecimentos',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='estabelecimentos',
            name='rua',
        ),
    ]
