# Generated by Django 3.2.4 on 2021-08-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0024_auto_20210829_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='publico_eventos',
            name='qtdPessoasP',
            field=models.IntegerField(null=True, verbose_name='qtdPessoas'),
        ),
    ]
