# Generated by Django 3.2.4 on 2021-08-29 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0026_auto_20210829_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='dataEvento',
            new_name='data_Evento',
        ),
        migrations.RenameField(
            model_name='eventos',
            old_name='horaFinal',
            new_name='hora_Final',
        ),
        migrations.RenameField(
            model_name='eventos',
            old_name='horaInicial',
            new_name='hora_Inicial',
        ),
        migrations.RenameField(
            model_name='eventos',
            old_name='qtdPessoas',
            new_name='qtd_Pessoas',
        ),
    ]
