# Generated by Django 3.2.4 on 2021-08-29 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0027_auto_20210829_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='data_Evento',
            new_name='dataEvento',
        ),
        migrations.RenameField(
            model_name='eventos',
            old_name='hora_Final',
            new_name='horaFinal',
        ),
        migrations.RenameField(
            model_name='eventos',
            old_name='hora_Inicial',
            new_name='horaInicial',
        ),
        migrations.RenameField(
            model_name='eventos',
            old_name='qtd_Pessoas',
            new_name='qtdPessoas',
        ),
    ]
