# Generated by Django 3.1.7 on 2021-09-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0029_auto_20210901_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='titulo',
            field=models.CharField(max_length=15, null=True, verbose_name='titulo'),
        ),
    ]
