# Generated by Django 3.1.7 on 2021-09-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0030_auto_20210902_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='titulo',
            field=models.CharField(max_length=20, null=True, verbose_name='titulo'),
        ),
    ]
