# Generated by Django 3.2.4 on 2021-09-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0034_alter_eventos_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicogeral',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='telefone'),
        ),
    ]
