# Generated by Django 3.2.4 on 2021-09-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0037_alter_eventos_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='titulo',
            field=models.CharField(max_length=30, null=True, verbose_name='titulo'),
        ),
    ]
