# Generated by Django 3.2.4 on 2021-09-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0038_alter_eventos_titulo'),
        ('appsite', '0038_auto_20210902_2353'),
    ]

    operations = [
    ]
