# Generated by Django 3.2.6 on 2021-09-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0040_auto_20210909_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publico_eventos',
            name='idEvento',
        ),
        migrations.RemoveField(
            model_name='publico_eventos',
            name='idPessoa',
        ),
        migrations.DeleteModel(
            name='Eventos',
        ),
        migrations.DeleteModel(
            name='Publico_Eventos',
        ),
    ]
