# Generated by Django 3.2.4 on 2021-09-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0041_auto_20210911_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, null=True, verbose_name='titulo')),
                ('descricao', models.CharField(max_length=100, null=True, verbose_name='descricao')),
                ('qtdPessoas', models.IntegerField(verbose_name='qtdPessoas')),
                ('dataEvento', models.CharField(max_length=100, null=True, verbose_name='dataEvento')),
                ('horaInicial', models.CharField(max_length=100, verbose_name='horaInicial')),
                ('horaFinal', models.CharField(max_length=100, verbose_name='horaFinal')),
                ('local', models.CharField(max_length=100, null=True, verbose_name='local')),
                ('foto', models.FileField(null=True, upload_to='img/%Y/%m/%d')),
            ],
        ),
    ]
