# Generated by Django 3.2.4 on 2021-09-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0043_alter_eventos_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='foto',
            field=models.FileField(null=True, upload_to='img/%Y/%m/%d'),
        ),
    ]
