# Generated by Django 3.2.6 on 2021-09-11 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0041_auto_20210911_1035'),
        ('appsite2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='id_estabelecimento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appsite.estabelecimentos'),
        ),
        migrations.CreateModel(
            name='Publico_Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtdPessoasP', models.IntegerField(null=True, verbose_name='qtdPessoas')),
                ('idEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsite2.eventos')),
                ('idPessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsite.publicogeral')),
            ],
        ),
    ]
